### ISSUE TITLE
cron问题

### ISSUE THREAD

**Issue by EverCurse** [prprprus/scheduler#1]
例如crontab */1 这种 我需要一秒执行一次 我看文档好像还不能完成这个每秒一次的需求

**Comment by prprprus** [comment]
你好，是可以的，如下：

```Go
jobID := s.Every().Do(task)
```

确实是文档没有描述清楚，我会在文档增加说明的，谢谢你的提醒 👍

**Comment by prprprus** [comment]
已经更新了文档和例子😄 @EverCurse

**Comment by ghost** [comment]
@prprprus 非常感谢 正在学习你的代码
