### ISSUE TITLE
失败重试，怎么实现

### ISSUE THREAD

**Issue by 2892931976** [prprprus/scheduler#2]
失败重试，用你这个库怎么实现，主要调用那几个函数，还是你的库自己实现了，失败重试

**Comment by prprprus** [comment]
你好，已经实现了简单的重试，[这里](https://github.com/prprprus/scheduler/blob/master/scheduler.go#L293)

**Comment by 2892931976** [comment]
能不能提供接口或函数，让开发者自己定义重试内容

**Comment by prprprus** [comment]
这个建议很棒啊👍，考虑提个 pr 吗😏
