### ISSUE TITLE
是否能让定时调度的是否，每个task方法有最大的实例数

### ISSUE THREAD

**Issue by cg831344** [prprprus/scheduler#3]
我的意思是，如果每秒进行，发现上一次的task没有完成就跳过这一秒的执行

**Comment by prprprus** [comment]
你好 @cg831344

---

先感谢你的建议~

起初的设计是 task 之间是相互独立的，你描述的是 task 之间有依赖关系的情况，我把 issue 标记成 enhancement 吧

**Comment by cg831344** [comment]
好些，谢谢，相同的task，在同一时间只能有一个实例运行。
